// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClOahUFdwOG2XKb4L17Uw5v46d_ts_b3Y',
    appId: '1:70794252848:web:3d6730561d76a6aabe13f5',
    messagingSenderId: '70794252848',
    projectId: 'authtutorial-8e0e1',
    authDomain: 'authtutorial-8e0e1.firebaseapp.com',
    storageBucket: 'authtutorial-8e0e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1xYGToX0m9D-mqQiWmyST4_Wni0y-O24',
    appId: '1:70794252848:android:3286466a6631c0e7be13f5',
    messagingSenderId: '70794252848',
    projectId: 'authtutorial-8e0e1',
    storageBucket: 'authtutorial-8e0e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBParX_9mWctTPNrTs2FhnTgQ1BxXAqERs',
    appId: '1:70794252848:ios:cf33d0fedb277047be13f5',
    messagingSenderId: '70794252848',
    projectId: 'authtutorial-8e0e1',
    storageBucket: 'authtutorial-8e0e1.firebasestorage.app',
    androidClientId: '70794252848-rtenf3b32bn5hs4k0qp5ts94evvjidt5.apps.googleusercontent.com',
    iosClientId: '70794252848-qqmp8bol7ahefgnf1emc5grf3q7erpt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBParX_9mWctTPNrTs2FhnTgQ1BxXAqERs',
    appId: '1:70794252848:ios:cf33d0fedb277047be13f5',
    messagingSenderId: '70794252848',
    projectId: 'authtutorial-8e0e1',
    storageBucket: 'authtutorial-8e0e1.firebasestorage.app',
    androidClientId: '70794252848-rtenf3b32bn5hs4k0qp5ts94evvjidt5.apps.googleusercontent.com',
    iosClientId: '70794252848-qqmp8bol7ahefgnf1emc5grf3q7erpt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClOahUFdwOG2XKb4L17Uw5v46d_ts_b3Y',
    appId: '1:70794252848:web:ef3c92b9b0c1a0cfbe13f5',
    messagingSenderId: '70794252848',
    projectId: 'authtutorial-8e0e1',
    authDomain: 'authtutorial-8e0e1.firebaseapp.com',
    storageBucket: 'authtutorial-8e0e1.firebasestorage.app',
  );
}
